"""
Agent File Registry - Tracks files generated by remote agents per session.

When a remote agent generates a file (like an image), it uploads to blob storage
at a generic path like `image-generator/{uuid}/filename.png`. The host backend
needs to associate that file with the user's session so it shows up in their
file history.

This registry provides:
1. In-memory tracking of agent-generated files per session
2. Persistence to a local JSON file for restart resilience
3. Methods to register new files and list files for a session
"""

import json
import os
import threading
import uuid
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any, Optional

# Thread lock for safe concurrent access
_lock = threading.Lock()

# In-memory registry: {session_id: [file_records]}
_registry: Dict[str, List[Dict[str, Any]]] = {}

# Directory for persisting the registry
REGISTRY_DIR = Path(__file__).resolve().parent.parent / "data"
REGISTRY_FILE = REGISTRY_DIR / "agent_files_registry.json"


def _load_registry():
    """Load registry from disk on startup."""
    global _registry
    try:
        if REGISTRY_FILE.exists():
            with open(REGISTRY_FILE, 'r') as f:
                _registry = json.load(f)
                print(f"[AgentFileRegistry] Loaded {sum(len(v) for v in _registry.values())} files for {len(_registry)} sessions")
    except Exception as e:
        print(f"[AgentFileRegistry] Failed to load registry: {e}")
        _registry = {}


def _save_registry():
    """Persist registry to disk."""
    try:
        REGISTRY_DIR.mkdir(parents=True, exist_ok=True)
        with open(REGISTRY_FILE, 'w') as f:
            json.dump(_registry, f, indent=2, default=str)
    except Exception as e:
        print(f"[AgentFileRegistry] Failed to save registry: {e}")


def register_agent_file(
    session_id: str,
    uri: str,
    filename: str,
    content_type: str = "application/octet-stream",
    size: int = 0,
    source_agent: Optional[str] = None,
    file_id: Optional[str] = None
) -> Dict[str, Any]:
    """
    Register a file generated by a remote agent for a session.
    
    Args:
        session_id: The user's session ID
        file_id: Unique ID for this file
        filename: The filename
        uri: The blob storage URI (with SAS token)
        content_type: MIME type
        size: File size in bytes
        source_agent: Name of the agent that generated the file
        
    Returns:
        The created file record
    """
    with _lock:
        if session_id not in _registry:
            _registry[session_id] = []
        
        # Check for duplicates by URI (strip query params to compare base URL)
        base_uri = uri.split('?')[0] if '?' in uri else uri
        existing = next((f for f in _registry[session_id] if f.get('uri', '').split('?')[0] == base_uri), None)
        if existing:
            print(f"[AgentFileRegistry] File already registered: {filename}")
            return existing
        
        # Generate file_id if not provided
        actual_file_id = file_id or str(uuid.uuid4())
        
        file_record = {
            "id": actual_file_id,
            "filename": filename,
            "originalName": filename,
            "size": size,
            "contentType": content_type,
            "uploadedAt": datetime.utcnow().isoformat(),
            "uri": uri,
            "sourceAgent": source_agent,
            "type": "agent_generated"
        }
        
        _registry[session_id].append(file_record)
        print(f"[AgentFileRegistry] Registered file for session {session_id[:8]}...: {filename}")
        
        # Persist to disk
        _save_registry()
        
        return file_record


def get_agent_files(session_id: str) -> List[Dict[str, Any]]:
    """
    Get all agent-generated files for a session.
    
    Args:
        session_id: The user's session ID
        
    Returns:
        List of file records
    """
    with _lock:
        return list(_registry.get(session_id, []))


def clear_session_files(session_id: str) -> int:
    """
    Clear all agent files for a session.
    
    Args:
        session_id: The user's session ID
        
    Returns:
        Number of files cleared
    """
    with _lock:
        count = len(_registry.get(session_id, []))
        if session_id in _registry:
            del _registry[session_id]
            _save_registry()
        return count


def get_all_sessions() -> List[str]:
    """Get all session IDs that have registered files."""
    with _lock:
        return list(_registry.keys())


# Load registry on module import
_load_registry()
