-- Agent Files Registry Table
-- Tracks files generated by remote agents (images, videos, documents) per user session

CREATE TABLE IF NOT EXISTS agent_files (
    -- Primary key
    id UUID PRIMARY KEY,
    
    -- Session association
    session_id VARCHAR(255) NOT NULL,
    
    -- File metadata
    filename VARCHAR(500) NOT NULL,
    original_name VARCHAR(500),
    size BIGINT DEFAULT 0,
    content_type VARCHAR(255) DEFAULT 'application/octet-stream',
    
    -- Timestamps
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Storage location
    uri TEXT NOT NULL,  -- Azure Blob Storage URL with SAS token
    
    -- Source tracking
    source_agent VARCHAR(255),
    file_type VARCHAR(50) DEFAULT 'agent_generated',
    
    -- Indexes for common queries
    CONSTRAINT agent_files_file_type_check CHECK (file_type IN ('agent_generated', 'user_uploaded', 'system'))
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_agent_files_session_id ON agent_files(session_id);
CREATE INDEX IF NOT EXISTS idx_agent_files_source_agent ON agent_files(source_agent);
CREATE INDEX IF NOT EXISTS idx_agent_files_uploaded_at ON agent_files(uploaded_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_files_file_type ON agent_files(file_type);
CREATE INDEX IF NOT EXISTS idx_agent_files_content_type ON agent_files(content_type);

-- Composite index for session listing (most common query)
CREATE INDEX IF NOT EXISTS idx_agent_files_session_time ON agent_files(session_id, uploaded_at DESC);

COMMENT ON TABLE agent_files IS 'Registry of files generated by remote agents per user session';
COMMENT ON COLUMN agent_files.id IS 'Unique identifier for the file';
COMMENT ON COLUMN agent_files.session_id IS 'User session that owns this file';
COMMENT ON COLUMN agent_files.filename IS 'Current filename';
COMMENT ON COLUMN agent_files.original_name IS 'Original filename when uploaded/generated';
COMMENT ON COLUMN agent_files.size IS 'File size in bytes';
COMMENT ON COLUMN agent_files.content_type IS 'MIME type (e.g., image/png, video/mp4)';
COMMENT ON COLUMN agent_files.uploaded_at IS 'When the file was uploaded/generated';
COMMENT ON COLUMN agent_files.uri IS 'Azure Blob Storage URL with SAS token';
COMMENT ON COLUMN agent_files.source_agent IS 'Name of the agent that generated this file';
COMMENT ON COLUMN agent_files.file_type IS 'Type of file: agent_generated, user_uploaded, or system';
